language: python

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.11.10

before_install:
  - export DJANGO_SETTINGS_MODULE="gis_csdt.settings"
  - export PYTHONPATH="/usr/local/lib/python2.7/dist-packages"
  - export PIP_USE_MIRRORS=true

install:
  - pip install setuptools --upgrade
  - "bash bin/travis.sh"
  - python -m pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - pip install coveralls
  - pip install flake8
  - sudo service postgresql restart

script:
  - python manage.py migrate --noinput
  - coverage run --source="." manage.py test

after_success:
  - pip freeze
  - echo Uploading code coverage data ...; coveralls
