# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_teams', '0006_auto_20180413_1441'),
        ('gis_csdt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useName', models.CharField(default=b'name', max_length=150)),
                ('setName', models.CharField(default=b'name', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='datafield',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='denominator',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='mapelement',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='mapelement',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sensor',
        ),
        migrations.AlterUniqueTogether(
            name='observationvalue',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='observationvalue',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='city_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='county_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='field1_en',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='field1_name',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='field2_en',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='field2_name',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='field3_en',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='field3_name',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='lat_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='lon_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='name_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='needs_geocoding',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='remote_id_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='state_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='street_field',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='zipcode_field',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='county',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='geocoded',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='state',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='street',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_teams.Team'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DataElement',
        ),
        migrations.DeleteModel(
            name='DataField',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='ObservationValue',
        ),
        migrations.AddField(
            model_name='fieldorder',
            name='Dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_csdt.Dataset'),
        ),
        migrations.AddField(
            model_name='fieldorder',
            name='Field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_csdt.Field'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='fields',
            field=models.ManyToManyField(through='gis_csdt.FieldOrder', to='gis_csdt.Field'),
        ),
    ]
