# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0002_auto_20180413_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldorder',
            old_name='Dataset',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='fieldorder',
            old_name='Field',
            new_name='field',
        ),
    ]
