# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0002_auto_20180223_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='user',
        ),
    ]
