# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0003_auto_20180523_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
