# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0004_datapoint_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='datapoints',
            field=models.ManyToManyField(to='gis_csdt.DataPoint'),
        ),
    ]
