# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0004_datapoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=18),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='lon',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=18),
        ),
    ]
