# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0005_auto_20180224_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='lon',
        ),
    ]
