# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_csdt', '0005_auto_20180529_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='point',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='user',
        ),
        migrations.AddField(
            model_name='sensor',
            name='mappoint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gis_csdt.MapPoint'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
