# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0006_auto_20180604_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mappoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gis_csdt.MapPoint'),
        ),
    ]
