# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_csdt', '0007_auto_20180604_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
